# Generated by Django 5.1.3 on 2024-12-04 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_order_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('food', 'Food'), ('clothes', 'Clothes'), ('electronics', 'Electronics')], default='food', max_length=20),
        ),
    ]
